name: flutter-version-number
description: 'Reads the version number of the pubspec.yaml'
author: sadi304
branding:
  icon: 'archive'
  color: 'green'
inputs:
  file-path:
    description: "Path to your pubspec.yaml. Default is ./pubspec.yaml"
    required: false
    default: "./pubspec.yaml"
outputs:
  full-version:
    description: "Full version including build number"
    value: ${{ steps.read-yaml.outputs.full-version }}
  version:
    description: "Version number"
    value: ${{ steps.read-yaml.outputs.version }}
  build-number:
    description: "Version number"
    value: ${{ steps.read-yaml.outputs.build-number }}
runs:
  using: "composite"
  steps:
    - id: read-yaml
      run: |
        FULL_VERSION=`cat ${{inputs.file-path}} | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        VERSION=${FULL_VERSION%+*}
        BUILD_NUMBER=${FULL_VERSION#*+}
        echo "::set-output name=full-version::$(echo $FULL_VERSION)"
        echo "::set-output name=version::$(echo $VERSION)"
        echo "::set-output name=build-number::$(echo $BUILD_NUMBER)"
      shell: bash
