on:
  push:
    branches:
      - main
name: Test outputs
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: read-version
        uses: sadi304/flutter-version-number-action@main
        with:
          file-path: example/pubspec.yaml
      - uses: nick-invision/assert-action@v1
        with:
          expected: 0.0.1+1
          actual: ${{ steps.read-version.outputs.full-version }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: 0.0.1
          actual: ${{ steps.read-version.outputs.version }}
      - uses: nick-invision/assert-action@v1
        with:
          expected: 1
          actual: ${{ steps.read-version.outputs.build-number }}

